### ISSUE TITLE
请求适配一下MIUI13eu版本地化后的传送门

### ISSUE THREAD

**Issue by nonlog** [Haocen2004/PortalHook#3]
版本号是2.5.18，https://blog.minamigo.moe/archives/184
这是本地化模块的地址

**Comment by Haocen2004** [comment]
我看方法啥是一样的啊
能发一下log吗

**Comment by nonlog** [comment]
> 我看方法啥是一样的啊 能发一下log吗

怎么得到log？

**Comment by nonlog** [comment]
> 我看方法啥是一样的啊 能发一下log吗

换了个开发版，又能用了

**Comment by Haocen2004** [comment]
未继续反馈无法使用 issue暂时关闭
